#!/bin/bash
set -e

echo "🔒 Àpínlẹ̀rọ Security Setup - All Layers"
echo "========================================"
echo ""
echo "This will set up all 4 security layers:"
echo "  Layer 1: Secret Scanning & Code Security (GitHub + Snyk)"
echo "  Layer 2: Container Vulnerability Scanning (Grype + Syft)"
echo "  Layer 3: Runtime Monitoring & Error Tracking (Sentry + Uptime Kuma)"
echo "  Layer 4: AI/LLM Observability (Helicone + Langfuse)"
echo ""
echo "Total cost: £0/month (all free tiers)"
echo ""

read -p "Press Enter to continue or Ctrl+C to cancel..."

# Get the directory where this script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo ""
echo "================================"
echo "Starting Layer 1..."
echo "================================"
bash "$SCRIPT_DIR/setup-layer1.sh"

echo ""
echo "================================"
echo "Starting Layer 2..."
echo "================================"
bash "$SCRIPT_DIR/setup-layer2.sh"

echo ""
echo "================================"
echo "Starting Layer 3..."
echo "================================"
bash "$SCRIPT_DIR/setup-layer3.sh"

echo ""
echo "================================"
echo "Starting Layer 4..."
echo "================================"
bash "$SCRIPT_DIR/setup-layer4.sh"

echo ""
echo "🎉 All security layers configured!"
echo ""
echo "📋 Next Steps Checklist:"
echo "========================"
echo ""
echo "GitHub Repository Settings:"
echo "  [ ] Enable Secret Scanning"
echo "  [ ] Enable Push Protection"
echo "  [ ] Enable Code Scanning (CodeQL)"
echo "  [ ] Add SNYK_TOKEN to repository secrets"
echo ""
echo "Environment Variables (add to .env.local and Railway):"
echo "  [ ] VITE_SENTRY_DSN"
echo "  [ ] SENTRY_AUTH_TOKEN"
echo "  [ ] SNYK_TOKEN"
echo "  [ ] HELICONE_API_KEY"
echo "  [ ] LANGFUSE_SECRET_KEY"
echo "  [ ] LANGFUSE_PUBLIC_KEY"
echo ""
echo "Deployment:"
echo "  [ ] Deploy Uptime Kuma on Railway"
echo "  [ ] Configure monitors in Uptime Kuma"
echo "  [ ] Set up notification channels"
echo ""
echo "Verification:"
echo "  [ ] Push test file with fake API key (GitHub should block)"
echo "  [ ] Run 'npm run security:scan' (should show CVE report)"
echo "  [ ] Trigger test error (should appear in Sentry)"
echo "  [ ] Make LLM call (should appear in Helicone & Langfuse)"
echo ""
echo "📚 For detailed information, see SECURITY.md"
